#!/usr/bin/env node
/**
 * Hades connector shim — the canonical userland HTTP endpoint.
 *
 * A Connector is the kernel's HTTP capability boundary. The kernel governs the
 * route (NetworkPolicy) and injects discovery (brain env); the endpoint itself
 * is userland — a deployed image the brain calls over HTTP. This shim is the
 * default: a tiny dependency-free HTTP proxy that forwards requests to an
 * upstream URL, injecting an auth header read from the environment.
 *
 * It is deliberately minimal and swappable. A real connector (a GitHub client,
 * a browser, a vector DB) is its own image implementing whatever the capability
 * needs — the kernel only routes to it. Think of this as the default Linux
 * device driver you can replace.
 *
 * Configuration (env):
 *   HADES_CONNECTOR_TARGET  upstream URL to proxy to (required)
 *   HADES_CONNECTOR_AUTH    a header value to inject as Authorization (optional;
 *                           usually injected from a k8s Secret via envFrom)
 *   HADES_CONNECTOR_HEADER  header name for the auth (default "Authorization")
 *   PORT                    listen port (default 8080)
 *
 * The brain calls this endpoint via its `hades_call_<name>` tool, generated by
 * ConnectorToolRegistrar from the kernel-injected HADES_CONNECTORS manifest.
 */
import http from "node:http";

const TARGET = process.env.HADES_CONNECTOR_TARGET;
const AUTH = process.env.HADES_CONNECTOR_AUTH;
const AUTH_HEADER = process.env.HADES_CONNECTOR_HEADER ?? "Authorization";
const PORT = Number(process.env.PORT ?? 8080);

if (!TARGET) {
    console.error("hades-connector: HADES_CONNECTOR_TARGET is required (the upstream URL to proxy to)");
    process.exit(1);
}

let target;
try {
    target = new URL(TARGET);
} catch {
    console.error(`hades-connector: HADES_CONNECTOR_TARGET is not a valid URL: ${TARGET}`);
    process.exit(1);
}

const server = http.createServer(async (req, res) => {
    // Build the upstream URL: same pathname + query as the inbound request.
    const upstream = new URL(req.url ?? "/", target);
    // Forward the request body (if any) and a copy of the headers, then
    // inject the auth header from the environment.
    const chunks = [];
    for await (const chunk of req) chunks.push(chunk);
    const body = chunks.length ? Buffer.concat(chunks) : undefined;
    const headers = { ...req.headers, host: upstream.host };
    if (AUTH) headers[AUTH_HEADER.toLowerCase()] = AUTH;
    try {
        const upstreamRes = await fetch(upstream, {
            method: req.method ?? "GET",
            headers,
            ...(body ? { body } : {}),
        });
        res.writeHead(upstreamRes.status, { "content-type": upstreamRes.headers.get("content-type") ?? "application/json" });
        const text = await upstreamRes.text();
        res.end(text);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        res.writeHead(502, { "content-type": "application/json" });
        res.end(JSON.stringify({ error: "connector upstream error", message }));
    }
});

server.listen(PORT, () => {
    console.log(`hades-connector listening on :${PORT} → ${TARGET.origin}`);
});
