export type PrimitiveDecision = "adopt" | "defer" | "reject";
export type PrimitiveLayer = "kernel" | "sandbox" | "gateway" | "tooling" | "workflow" | "interop" | "ux";
export type PrimitiveImplementation = "runtime" | "resource" | "spec" | "future" | "never";

export type AgentOSPrimitive = {
    id: string;
    name: string;
    layer: PrimitiveLayer;
    decision: PrimitiveDecision;
    implementation: PrimitiveImplementation;
    why: string;
    mapsToKinds: string[];
    relatedConcepts?: string[];
    sources: string[];
};

export const PRIMITIVES: AgentOSPrimitive[] = [
    {
        id: "linux.namespaces",
        name: "Linux namespaces",
        layer: "sandbox",
        decision: "adopt",
        implementation: "resource",
        why: "PID, mount, user, network, IPC, and UTS boundaries are the correct substrate for Hands isolation; agents should request sandbox profiles, not raw namespace operations.",
        mapsToKinds: ["SandboxProfile", "Hands"],
        sources: ["Linux", "Kubernetes pods", "OpenClaw sandboxing"],
    },
    {
        id: "linux.cgroups",
        name: "cgroups resource control",
        layer: "sandbox",
        decision: "adopt",
        implementation: "resource",
        why: "Hands and brain runtimes need explicit CPU, memory, process, and IO budgets to avoid noisy-neighbor failure and runaway tool loops.",
        mapsToKinds: ["SandboxProfile", "Hands", "BrainBinding"],
        sources: ["Linux", "Kubernetes resources"],
    },
    {
        id: "linux.capabilities-seccomp",
        name: "Linux capabilities and seccomp",
        layer: "sandbox",
        decision: "adopt",
        implementation: "resource",
        why: "Tool sandboxes should drop ambient host powers and block unneeded syscalls. This belongs in sandbox profiles, not model-visible tools.",
        mapsToKinds: ["SandboxProfile"],
        relatedConcepts: ["Kubernetes securityContext"],
        sources: ["Linux", "Kubernetes securityContext"],
    },
    {
        id: "linux.mounts",
        name: "Mounts and volume projections",
        layer: "kernel",
        decision: "adopt",
        implementation: "runtime",
        why: "Home, workspace, scratch, and secret projections are the concrete filesystem primitives for agent userland. Mount policy must prevent symlink/bind escape.",
        mapsToKinds: ["Home", "Hands", "SecretLease"],
        sources: ["Linux", "Kubernetes PVC/projected volumes", "OpenClaw bind validation"],
    },
    {
        id: "linux.timers",
        name: "Timers and cron",
        layer: "kernel",
        decision: "adopt",
        implementation: "runtime",
        why: "Schedules are core autonomy. Hades should own semantic schedules and may compile to Kubernetes CronJobs later.",
        mapsToKinds: ["Schedule"],
        sources: ["cron", "systemd timers", "Kubernetes CronJob", "OpenClaw cron"],
    },
    {
        id: "linux.inotify",
        name: "Filesystem watch notifications",
        layer: "kernel",
        decision: "defer",
        implementation: "future",
        why: "Useful for Home/project indexing and reactive workflows, but not required for the first reliable agent loop.",
        mapsToKinds: ["Home", "Workflow"],
        sources: ["Linux inotify/fanotify"],
    },
    {
        id: "linux.pty",
        name: "PTY attach",
        layer: "ux",
        decision: "adopt",
        implementation: "future",
        why: "Humans need controlled live attachment to Hands and long-running jobs, but agents should use structured exec APIs first.",
        mapsToKinds: ["Hands", "Run"],
        sources: ["terminal", "tmux", "Kubernetes exec/attach"],
    },
    {
        id: "gateway.per-agent-listeners",
        name: "Per-agent gateway listeners",
        layer: "gateway",
        decision: "adopt",
        implementation: "runtime",
        why: "OpenClaw validates a single Gateway daemon owning many channels, but Hades needs listener attachment per agent/session to avoid Wren hardcoding.",
        mapsToKinds: ["Gateway", "Listener"],
        sources: ["OpenClaw Gateway", "Hades Listener model"],
    },
    {
        id: "gateway.nodes",
        name: "Paired device nodes",
        layer: "gateway",
        decision: "adopt",
        implementation: "resource",
        why: "Voice, camera, canvas, location, and push surfaces belong on paired nodes with declared capabilities, not inside brain/hands pods.",
        mapsToKinds: ["Node", "Gateway", "CapabilityGrant"],
        sources: ["OpenClaw nodes", "OpenClaw device pairing"],
    },
    {
        id: "gateway.voice",
        name: "Voice wake and talk mode",
        layer: "ux",
        decision: "defer",
        implementation: "future",
        why: "Voice is valuable for resident agents, but it is an edge node capability. The kernel only needs the node/gateway event contract first.",
        mapsToKinds: ["Node", "Listener"],
        sources: ["OpenClaw Voice Wake", "OpenClaw Talk Mode"],
    },
    {
        id: "gateway.canvas",
        name: "Live canvas / visual surface",
        layer: "ux",
        decision: "defer",
        implementation: "future",
        why: "Useful for rich control rooms and agent-made views, but not a kernel primitive until API/event contracts stabilize.",
        mapsToKinds: ["Node", "Gateway"],
        relatedConcepts: ["Artifact"],
        sources: ["OpenClaw Canvas", "A2UI"],
    },
    {
        id: "mcp.brokered-tools",
        name: "Brokered MCP tool providers",
        layer: "tooling",
        decision: "adopt",
        implementation: "resource",
        why: "MCP should be discovered, filtered, cooled down, and audited through a broker. Attaching every MCP server to every agent pod is credential and policy sprawl.",
        mapsToKinds: ["ToolProvider", "CapabilityGrant", "Run"],
        sources: ["MCP", "ACP MCP-over-ACP", "OpenClaw bundle-mcp policy"],
    },
    {
        id: "acp.external-sessions",
        name: "ACP external harness sessions",
        layer: "interop",
        decision: "adopt",
        implementation: "resource",
        why: "ACP/acpx is the right bridge to Claude Code, Codex, OpenClaw, Gemini, and other harnesses. Hades should track external sessions explicitly rather than scrape PTYs.",
        mapsToKinds: ["ExternalSession", "Workflow", "Run"],
        sources: ["ACP", "acpx", "OpenClaw ACP agents"],
    },
    {
        id: "workflow.dag",
        name: "Dynamic workflow DAGs",
        layer: "workflow",
        decision: "adopt",
        implementation: "resource",
        why: "Some orchestration should be deterministic and inspectable outside model turns: parallel research, review/fix loops, build/test/deploy chains.",
        mapsToKinds: ["Workflow", "Run", "Approval"],
        sources: ["acpx flows", "Claude Agent SDK research agents", "Linux job control"],
    },
    {
        id: "hooks.permission-callbacks",
        name: "Permission and tool hooks",
        layer: "kernel",
        decision: "adopt",
        implementation: "future",
        why: "Claude Agent SDK and OpenClaw show hooks are useful, but Hades should express them as policy/approval events rather than arbitrary plugin code in the kernel.",
        mapsToKinds: ["Approval", "CapabilityGrant", "Run"],
        sources: ["Claude Agent SDK hooks", "OpenClaw permission hooks"],
    },
    {
        id: "linux.dbus-raw",
        name: "Raw D-Bus session bus access",
        layer: "ux",
        decision: "reject",
        implementation: "never",
        why: "Desktop integration is useful, but raw D-Bus is too broad. Expose narrow node/gateway commands instead.",
        mapsToKinds: ["Node"],
        sources: ["Linux D-Bus"],
    },
    {
        id: "linux.ptrace-raw",
        name: "Raw ptrace/perf debugging",
        layer: "sandbox",
        decision: "reject",
        implementation: "never",
        why: "ptrace is a sandbox escape hazard. Debugging should happen through explicit profiles and human-approved hands, not default agent capabilities.",
        mapsToKinds: ["SandboxProfile"],
        sources: ["Linux ptrace", "seccomp"],
    },
    {
        id: "mcp.sidecar-sprawl",
        name: "Per-agent MCP sidecar sprawl",
        layer: "tooling",
        decision: "reject",
        implementation: "never",
        why: "One MCP sidecar per server per agent spreads credentials and makes dynamic tool policy/cooldown difficult. Use brokered ToolProviders.",
        mapsToKinds: ["ToolProvider"],
        sources: ["MCP", "ACP MCP-over-ACP"],
    },
];
